[package]
name = "cpp-to-rust"
version = "0.1.0"
authors = ["timmonfette1 <monfette.timothy@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"

[lib]
name = "double_input"
crate-type = ["dylib"]
